### ISSUE TITLE
Remove Unused Variables for extra security

### ISSUE THREAD

**Issue by jack60612** [remilapeyre/vault-acme#13]
on line 129  and 102 in root/acme/path_certs.go there is an err variable that isn't used
and there is a unused each import on line 2 and a unused components variable on line 14 on /root/website/assets/js/index.js

**Comment by jack60612** [comment]
@remilapeyre

**Comment by remilapeyre** [comment]
Hi @jack60612, those errors should have been checked and an error should have been returned. Do you want to open a new PR to fix those?

**Comment by jack60612** [comment]
@remilapeyre im not that good with js but i just wanted to help you out by showing you the tool

**Comment by remilapeyre** [comment]
The JavaScript comes from https://github.com/hashcorp/vault so we should not change it. I will need to update the Go code and add a test to make sure it does not happen again thought.

**Comment by remilapeyre** [comment]
Thanks for the feedback @jack60612, now that I've found how to disable the JS warnings, I fixed the errors.
