### ISSUE TITLE
Please add SHA256SUMS file for releases

### ISSUE THREAD

**Issue by hongkongkiwi** [remilapeyre/vault-acme#17]
I'm downloading your code into a docker, it would be great if there was a SHA256SUMS file I can download for verification.

**Comment by remilapeyre** [comment]
Hi @hongkongkiwi, this is a good idea thanks. I will add this in the coming days.

**Comment by remilapeyre** [comment]
Thanks for the feedback @hongkongkiwi, I just made a new release with this file present.

**Comment by hongkongkiwi** [comment]
Thanks! 👍
