### ISSUE TITLE
Vault ACME should work with mlock enabled

### ISSUE THREAD

**Issue by remilapeyre** [remilapeyre/vault-acme#2]
From https://github.com/remilapeyre/vault-acme/issues/1#issuecomment-561456214

Enabling Vault ACME in Docker fails when `mlock` is enabled with a cryptic error message:

```text
#> vault secrets enable acme
Error enabling: Error making API request.

URL: POST http://139.162.27.172:22663/v1/sys/mounts/acme
Code: 400. Errors:

* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

I've not tested if the same happens without Docker.

**Comment by nvx** [comment]
I gave it a quick shot outside of docker and it ran fine with mlock enabled on FreeBSD

**Comment by remilapeyre** [comment]
It was actually documented at https://www.vaultproject.io/docs/configuration/#inlinecode-disable_mlock.

I updated the README with 6228da5b45e600f3a757195f1068df39d2777fba.
