### ISSUE TITLE
cloudflare: some credentials information are missing

### ISSUE THREAD

**Issue by jeromeza** [remilapeyre/vault-acme#23]
I can't get Cloudflare to work, I get the below error, this after trying:

```
#!/bin/bash

export CLOUDFLARE_EMAIL="my@domain.co.za"
export CLOUDFLARE_API_KEY="myglobalapikey"
export CF_API_EMAIL="my@domain.co.za"
export CF_API_KEY="myglobalapikey"

/Users/jerome/Downloads/vault/vault -v write acme/certs/domain.co.za \
    common_name=www.domain.co.za
```

* Failed to validate certificate signing request: cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN

I've tried this as EXPORT vars in my shell, and in a script format above (as I came across a Lego post suggesting this: https://github.com/go-acme/lego/issues/785)

Any ideas - I've tried both sets of variables as shown above...

It simply looks like the vars aren't being passed through to the Lego client?

Thanks!

**Comment by jeromeza** [comment]
Digging through old commits - around 0.6 iirc I found that there's an added provider_configuration that can be called, which lets you specify the value outside of a shell var, as part of a map.

**This seems to work:**
./vault write acme/accounts/jerome \
	contact=jerome@sheed.co.za \
	server_url=https://acme-staging-v02.api.letsencrypt.org/directory \
	terms_of_service_agreed=true \
	provider=cloudflare \
    provider_configuration={CF_API_KEY=mykey,CLOUDFLARE_EMAIL=jerome@sheed.co.za}

**Comment by remilapeyre** [comment]
Hi @jeromeza, I will close this issue. If you are still having troubles with setting the configuration please open it again.
