### ISSUE TITLE
How do I read a certificate run back?

### ISSUE THREAD

**Issue by jeromeza** [remilapeyre/vault-acme#24]
$ vault write acme/certs/yoonix.xyz
...
cert generates

$ vault read acme/certs/yoonix.xyz
Error reading acme/certs/yoonix.xyz: Error making API request.

URL: GET http://127.0.0.1:8200/v1/acme/certs/yoonix.xyz
Code: 405. Errors:

* 1 error occurred:
	* unsupported operation
	
-- 

Is this possible? 
I tried to check via the Vault GUI but the acme/ secrets engine is greyed out (and from a brief Google it appears not all engines work in the GUI - so I'm not sure that's the issue).

-- 

EDIT: Looks like a another 'vault write' request returns the cached cert - which as far as I understand is valid until it's cache ratio is hit - at which point it (potentially auto) renews?

**Comment by remilapeyre** [comment]
Hi @jeromeza,

> Looks like a another 'vault write' request returns the cached cert - which as far as I understand is valid until it's cache ratio is hit - at which point it (potentially auto) renews?

Yes, this is correct and that the way you should read certificates already created. Please let me know if you have any other question!
