### ISSUE TITLE
add built binaries to github releases

### ISSUE THREAD

**Issue by karl-tpio** [remilapeyre/vault-acme#8]
Hi!

I see that you're already using github actions to run tests against the code.

I'd like to request that this be extended slightly so that tested code is built and the resulting binaries are uploaded to the repo's "releases" section.

There's a simple github action to do just this:

https://github.com/actions/upload-release-asset

I'll be more than happy to contribute a PR for the `actions.yml` file to do so, if needed.

**Comment by remilapeyre** [comment]
Hi @karl-tpio, thanks for the idea, I implemented that in c4588479408c26f563e512b4699a23349af5e73c. I will try to tag a new version on each commit.
